codecov:
  notify:
    wait_for_ci: true

coverage:
  status:
    project:
      default:
        target: 45%
        threshold: 0%
    patch:
      default:
        target: auto

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false

ignore:
  - "**/*_test.c"
  - "libbubble/tests/**"

component_management:
  default_rules:
    statuses:
      - type: project
        target: 45%
  individual_components:
    - component_id: libbubble
      name: libbubble
      paths:
        - libbubble/**
    - component_id: bubblehub
      name: bubblehub
      paths:
        - bubblehub/**
